/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) jit_tmp_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s4[41] = {16, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 13, 17, 22, 22, 22, 22, 22, 0, 1, 2, 3, 4, 5, 6, 7, 0, 4, 1, 5, 8, 2, 6, 8, 9, 3, 7, 8, 9, 10};
static const casadi_int casadi_s5[39] = {9, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 16, 18, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 8, 8, 8, 0, 4, 1, 5, 2, 6, 3, 7};

casadi_real casadi_sq(casadi_real x) { return x*x;}

/* nlp:(x[16],p[])->(f,g[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0] ? arg[0][8] : 0;
  a1=100.;
  a2=1.;
  a3=arg[0] ? arg[0][0] : 0;
  a4=(a3-a2);
  a4=(1./a4);
  a5=arg[0] ? arg[0][4] : 0;
  a6=casadi_sq(a5);
  a7=2.;
  a6=(a6/a7);
  a4=(a4+a6);
  a4=(a2-a4);
  a4=(a1*a4);
  a4=(a0*a4);
  a6=arg[0] ? arg[0][9] : 0;
  a8=arg[0] ? arg[0][1] : 0;
  a9=(a8-a2);
  a9=(1./a9);
  a10=arg[0] ? arg[0][5] : 0;
  a11=casadi_sq(a10);
  a11=(a11/a7);
  a9=(a9+a11);
  a9=(a2-a9);
  a9=(a1*a9);
  a9=(a6*a9);
  a4=(a4+a9);
  a9=arg[0] ? arg[0][10] : 0;
  a11=arg[0] ? arg[0][2] : 0;
  a12=(a11-a2);
  a12=(1./a12);
  a13=arg[0] ? arg[0][6] : 0;
  a14=casadi_sq(a13);
  a14=(a14/a7);
  a12=(a12+a14);
  a12=(a2-a12);
  a12=(a1*a12);
  a12=(a9*a12);
  a4=(a4+a12);
  a12=arg[0] ? arg[0][11] : 0;
  a14=arg[0] ? arg[0][3] : 0;
  a15=(a14-a2);
  a15=(1./a15);
  a16=arg[0] ? arg[0][7] : 0;
  a17=casadi_sq(a16);
  a17=(a17/a7);
  a15=(a15+a17);
  a15=(a2-a15);
  a15=(a1*a15);
  a15=(a12*a15);
  a4=(a4+a15);
  a15=1.0000000000000000e-003;
  a17=(a0*a6);
  a18=(a0*a9);
  a17=(a17+a18);
  a18=(a0*a12);
  a17=(a17+a18);
  a18=(a6*a9);
  a17=(a17+a18);
  a18=(a6*a12);
  a17=(a17+a18);
  a18=(a9*a12);
  a17=(a17+a18);
  a17=(a17+a6);
  a7=(a7*a9);
  a17=(a17+a7);
  a7=3.;
  a7=(a7*a12);
  a17=(a17+a7);
  a15=(a15*a17);
  a4=(a4-a15);
  a4=(-a4);
  if (res[0]!=0) res[0][0]=a4;
  a4=5.;
  a15=arg[0] ? arg[0][12] : 0;
  a17=(a4+a15);
  a17=(a17-a3);
  if (res[1]!=0) res[1][0]=a17;
  a17=arg[0] ? arg[0][13] : 0;
  a3=(a4+a17);
  a7=1.0000000000000001e-001;
  a18=10.;
  a18=(a17-a18);
  a18=(a7*a18);
  a3=(a3-a18);
  a3=(a3-a8);
  if (res[1]!=0) res[1][1]=a3;
  a3=arg[0] ? arg[0][14] : 0;
  a8=(a4+a3);
  a18=5.9999999999999998e-001;
  a19=20.;
  a19=(a3-a19);
  a18=(a18*a19);
  a8=(a8-a18);
  a8=(a8-a2);
  a8=(a8-a11);
  if (res[1]!=0) res[1][2]=a8;
  a8=arg[0] ? arg[0][15] : 0;
  a4=(a4+a8);
  a11=50.;
  a11=(a8-a11);
  a7=(a7*a11);
  a4=(a4-a7);
  a7=18.;
  a4=(a4-a7);
  a4=(a4-a2);
  a4=(a4-a14);
  if (res[1]!=0) res[1][3]=a4;
  a5=(a1*a5);
  a5=(a5-a15);
  if (res[1]!=0) res[1][4]=a5;
  a10=(a1*a10);
  a10=(a10-a17);
  if (res[1]!=0) res[1][5]=a10;
  a13=(a1*a13);
  a13=(a13-a3);
  if (res[1]!=0) res[1][6]=a13;
  a1=(a1*a16);
  a1=(a1-a8);
  if (res[1]!=0) res[1][7]=a1;
  a0=(a0+a6);
  a0=(a0+a9);
  a0=(a0+a12);
  a0=(a0-a2);
  if (res[1]!=0) res[1][8]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void nlp_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* nlp_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_name_out(casadi_int i){
  switch (i) {
    case 0: return "f";
    case 1: return "g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* nlp_f:(x[16],p[])->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0] ? arg[0][8] : 0;
  a1=100.;
  a2=1.;
  a3=arg[0] ? arg[0][0] : 0;
  a3=(a3-a2);
  a3=(1./a3);
  a4=arg[0] ? arg[0][4] : 0;
  a4=casadi_sq(a4);
  a5=2.;
  a4=(a4/a5);
  a3=(a3+a4);
  a3=(a2-a3);
  a3=(a1*a3);
  a3=(a0*a3);
  a4=arg[0] ? arg[0][9] : 0;
  a6=arg[0] ? arg[0][1] : 0;
  a6=(a6-a2);
  a6=(1./a6);
  a7=arg[0] ? arg[0][5] : 0;
  a7=casadi_sq(a7);
  a7=(a7/a5);
  a6=(a6+a7);
  a6=(a2-a6);
  a6=(a1*a6);
  a6=(a4*a6);
  a3=(a3+a6);
  a6=arg[0] ? arg[0][10] : 0;
  a7=arg[0] ? arg[0][2] : 0;
  a7=(a7-a2);
  a7=(1./a7);
  a8=arg[0] ? arg[0][6] : 0;
  a8=casadi_sq(a8);
  a8=(a8/a5);
  a7=(a7+a8);
  a7=(a2-a7);
  a7=(a1*a7);
  a7=(a6*a7);
  a3=(a3+a7);
  a7=arg[0] ? arg[0][11] : 0;
  a8=arg[0] ? arg[0][3] : 0;
  a8=(a8-a2);
  a8=(1./a8);
  a9=arg[0] ? arg[0][7] : 0;
  a9=casadi_sq(a9);
  a9=(a9/a5);
  a8=(a8+a9);
  a2=(a2-a8);
  a1=(a1*a2);
  a1=(a7*a1);
  a3=(a3+a1);
  a1=1.0000000000000000e-003;
  a2=(a0*a4);
  a8=(a0*a6);
  a2=(a2+a8);
  a0=(a0*a7);
  a2=(a2+a0);
  a0=(a4*a6);
  a2=(a2+a0);
  a0=(a4*a7);
  a2=(a2+a0);
  a0=(a6*a7);
  a2=(a2+a0);
  a2=(a2+a4);
  a5=(a5*a6);
  a2=(a2+a5);
  a5=3.;
  a5=(a5*a7);
  a2=(a2+a5);
  a1=(a1*a2);
  a3=(a3-a1);
  a3=(-a3);
  if (res[0]!=0) res[0][0]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void nlp_f_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_f_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_f_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* nlp_f_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_f_name_out(casadi_int i){
  switch (i) {
    case 0: return "f";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* nlp_g:(x[16],p[])->(g[9]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7;
  a0=5.;
  a1=arg[0] ? arg[0][12] : 0;
  a2=(a0+a1);
  a3=arg[0] ? arg[0][0] : 0;
  a2=(a2-a3);
  if (res[0]!=0) res[0][0]=a2;
  a2=arg[0] ? arg[0][13] : 0;
  a3=(a0+a2);
  a4=1.0000000000000001e-001;
  a5=10.;
  a5=(a2-a5);
  a5=(a4*a5);
  a3=(a3-a5);
  a5=arg[0] ? arg[0][1] : 0;
  a3=(a3-a5);
  if (res[0]!=0) res[0][1]=a3;
  a3=arg[0] ? arg[0][14] : 0;
  a5=(a0+a3);
  a6=5.9999999999999998e-001;
  a7=20.;
  a7=(a3-a7);
  a6=(a6*a7);
  a5=(a5-a6);
  a6=1.;
  a5=(a5-a6);
  a7=arg[0] ? arg[0][2] : 0;
  a5=(a5-a7);
  if (res[0]!=0) res[0][2]=a5;
  a5=arg[0] ? arg[0][15] : 0;
  a0=(a0+a5);
  a7=50.;
  a7=(a5-a7);
  a4=(a4*a7);
  a0=(a0-a4);
  a4=18.;
  a0=(a0-a4);
  a0=(a0-a6);
  a4=arg[0] ? arg[0][3] : 0;
  a0=(a0-a4);
  if (res[0]!=0) res[0][3]=a0;
  a0=100.;
  a4=arg[0] ? arg[0][4] : 0;
  a4=(a0*a4);
  a4=(a4-a1);
  if (res[0]!=0) res[0][4]=a4;
  a4=arg[0] ? arg[0][5] : 0;
  a4=(a0*a4);
  a4=(a4-a2);
  if (res[0]!=0) res[0][5]=a4;
  a4=arg[0] ? arg[0][6] : 0;
  a4=(a0*a4);
  a4=(a4-a3);
  if (res[0]!=0) res[0][6]=a4;
  a4=arg[0] ? arg[0][7] : 0;
  a0=(a0*a4);
  a0=(a0-a5);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[0] ? arg[0][8] : 0;
  a5=arg[0] ? arg[0][9] : 0;
  a0=(a0+a5);
  a5=arg[0] ? arg[0][10] : 0;
  a0=(a0+a5);
  a5=arg[0] ? arg[0][11] : 0;
  a0=(a0+a5);
  a0=(a0-a6);
  if (res[0]!=0) res[0][8]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_g(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void nlp_g_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_g_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_g_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_g_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* nlp_g_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_g_name_out(casadi_int i){
  switch (i) {
    case 0: return "g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_g_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_g_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_g_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* nlp_grad:(x[16],p[],lam_f,lam_g[9])->(f,g[9],grad_gamma_x[16],grad_gamma_p[]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a4, a5, a6, a7, a8, a9;
  a0=arg[0] ? arg[0][8] : 0;
  a1=100.;
  a2=1.;
  a3=arg[0] ? arg[0][0] : 0;
  a4=(a3-a2);
  a5=(1./a4);
  a6=arg[0] ? arg[0][4] : 0;
  a7=casadi_sq(a6);
  a8=2.;
  a7=(a7/a8);
  a7=(a5+a7);
  a7=(a2-a7);
  a7=(a1*a7);
  a9=(a0*a7);
  a10=arg[0] ? arg[0][9] : 0;
  a11=arg[0] ? arg[0][1] : 0;
  a12=(a11-a2);
  a13=(1./a12);
  a14=arg[0] ? arg[0][5] : 0;
  a15=casadi_sq(a14);
  a15=(a15/a8);
  a15=(a13+a15);
  a15=(a2-a15);
  a15=(a1*a15);
  a16=(a10*a15);
  a9=(a9+a16);
  a16=arg[0] ? arg[0][10] : 0;
  a17=arg[0] ? arg[0][2] : 0;
  a18=(a17-a2);
  a19=(1./a18);
  a20=arg[0] ? arg[0][6] : 0;
  a21=casadi_sq(a20);
  a21=(a21/a8);
  a21=(a19+a21);
  a21=(a2-a21);
  a21=(a1*a21);
  a22=(a16*a21);
  a9=(a9+a22);
  a22=arg[0] ? arg[0][11] : 0;
  a23=arg[0] ? arg[0][3] : 0;
  a24=(a23-a2);
  a25=(1./a24);
  a26=arg[0] ? arg[0][7] : 0;
  a27=casadi_sq(a26);
  a27=(a27/a8);
  a27=(a25+a27);
  a27=(a2-a27);
  a27=(a1*a27);
  a28=(a22*a27);
  a9=(a9+a28);
  a28=1.0000000000000000e-003;
  a29=(a0*a10);
  a30=(a0*a16);
  a29=(a29+a30);
  a30=(a0*a22);
  a29=(a29+a30);
  a30=(a10*a16);
  a29=(a29+a30);
  a30=(a10*a22);
  a29=(a29+a30);
  a30=(a16*a22);
  a29=(a29+a30);
  a29=(a29+a10);
  a30=(a8*a16);
  a29=(a29+a30);
  a30=3.;
  a31=(a30*a22);
  a29=(a29+a31);
  a29=(a28*a29);
  a9=(a9-a29);
  a9=(-a9);
  if (res[0]!=0) res[0][0]=a9;
  a9=5.;
  a29=arg[0] ? arg[0][12] : 0;
  a31=(a9+a29);
  a31=(a31-a3);
  if (res[1]!=0) res[1][0]=a31;
  a31=arg[0] ? arg[0][13] : 0;
  a3=(a9+a31);
  a32=1.0000000000000001e-001;
  a33=10.;
  a33=(a31-a33);
  a33=(a32*a33);
  a3=(a3-a33);
  a3=(a3-a11);
  if (res[1]!=0) res[1][1]=a3;
  a3=arg[0] ? arg[0][14] : 0;
  a11=(a9+a3);
  a33=5.9999999999999998e-001;
  a34=20.;
  a34=(a3-a34);
  a34=(a33*a34);
  a11=(a11-a34);
  a11=(a11-a2);
  a11=(a11-a17);
  if (res[1]!=0) res[1][2]=a11;
  a11=arg[0] ? arg[0][15] : 0;
  a9=(a9+a11);
  a17=50.;
  a17=(a11-a17);
  a17=(a32*a17);
  a9=(a9-a17);
  a17=18.;
  a9=(a9-a17);
  a9=(a9-a2);
  a9=(a9-a23);
  if (res[1]!=0) res[1][3]=a9;
  a9=(a1*a6);
  a9=(a9-a29);
  if (res[1]!=0) res[1][4]=a9;
  a9=(a1*a14);
  a9=(a9-a31);
  if (res[1]!=0) res[1][5]=a9;
  a9=(a1*a20);
  a9=(a9-a3);
  if (res[1]!=0) res[1][6]=a9;
  a9=(a1*a26);
  a9=(a9-a11);
  if (res[1]!=0) res[1][7]=a9;
  a9=(a0+a10);
  a9=(a9+a16);
  a9=(a9+a22);
  a9=(a9-a2);
  if (res[1]!=0) res[1][8]=a9;
  a5=(a5/a4);
  a4=arg[2] ? arg[2][0] : 0;
  a9=(a0*a4);
  a9=(a1*a9);
  a5=(a5*a9);
  a2=arg[3] ? arg[3][0] : 0;
  a5=(a5+a2);
  a5=(-a5);
  if (res[2]!=0) res[2][0]=a5;
  a13=(a13/a12);
  a12=(a10*a4);
  a12=(a1*a12);
  a13=(a13*a12);
  a5=arg[3] ? arg[3][1] : 0;
  a13=(a13+a5);
  a13=(-a13);
  if (res[2]!=0) res[2][1]=a13;
  a19=(a19/a18);
  a18=(a16*a4);
  a18=(a1*a18);
  a19=(a19*a18);
  a13=arg[3] ? arg[3][2] : 0;
  a19=(a19+a13);
  a19=(-a19);
  if (res[2]!=0) res[2][2]=a19;
  a25=(a25/a24);
  a24=(a22*a4);
  a24=(a1*a24);
  a25=(a25*a24);
  a19=arg[3] ? arg[3][3] : 0;
  a25=(a25+a19);
  a25=(-a25);
  if (res[2]!=0) res[2][3]=a25;
  a6=(a6+a6);
  a25=5.0000000000000000e-001;
  a9=(a25*a9);
  a6=(a6*a9);
  a9=arg[3] ? arg[3][4] : 0;
  a11=(a1*a9);
  a6=(a6+a11);
  if (res[2]!=0) res[2][4]=a6;
  a14=(a14+a14);
  a12=(a25*a12);
  a14=(a14*a12);
  a12=arg[3] ? arg[3][5] : 0;
  a6=(a1*a12);
  a14=(a14+a6);
  if (res[2]!=0) res[2][5]=a14;
  a20=(a20+a20);
  a18=(a25*a18);
  a20=(a20*a18);
  a18=arg[3] ? arg[3][6] : 0;
  a14=(a1*a18);
  a20=(a20+a14);
  if (res[2]!=0) res[2][6]=a20;
  a26=(a26+a26);
  a25=(a25*a24);
  a26=(a26*a25);
  a25=arg[3] ? arg[3][7] : 0;
  a1=(a1*a25);
  a26=(a26+a1);
  if (res[2]!=0) res[2][7]=a26;
  a28=(a28*a4);
  a26=(a22*a28);
  a1=(a16*a28);
  a26=(a26+a1);
  a1=(a10*a28);
  a26=(a26+a1);
  a7=(a7*a4);
  a26=(a26-a7);
  a7=arg[3] ? arg[3][8] : 0;
  a26=(a26+a7);
  if (res[2]!=0) res[2][8]=a26;
  a26=(a22*a28);
  a26=(a28+a26);
  a1=(a16*a28);
  a26=(a26+a1);
  a1=(a0*a28);
  a26=(a26+a1);
  a15=(a15*a4);
  a26=(a26-a15);
  a26=(a26+a7);
  if (res[2]!=0) res[2][9]=a26;
  a8=(a8*a28);
  a22=(a22*a28);
  a8=(a8+a22);
  a22=(a10*a28);
  a8=(a8+a22);
  a22=(a0*a28);
  a8=(a8+a22);
  a21=(a21*a4);
  a8=(a8-a21);
  a8=(a8+a7);
  if (res[2]!=0) res[2][10]=a8;
  a30=(a30*a28);
  a16=(a16*a28);
  a30=(a30+a16);
  a10=(a10*a28);
  a30=(a30+a10);
  a0=(a0*a28);
  a30=(a30+a0);
  a27=(a27*a4);
  a30=(a30-a27);
  a30=(a30+a7);
  if (res[2]!=0) res[2][11]=a30;
  a2=(a2-a9);
  if (res[2]!=0) res[2][12]=a2;
  a2=(a32*a5);
  a12=(a12+a2);
  a5=(a5-a12);
  if (res[2]!=0) res[2][13]=a5;
  a33=(a33*a13);
  a18=(a18+a33);
  a13=(a13-a18);
  if (res[2]!=0) res[2][14]=a13;
  a32=(a32*a19);
  a25=(a25+a32);
  a19=(a19-a25);
  if (res[2]!=0) res[2][15]=a19;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_grad(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void nlp_grad_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_grad_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_grad_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int nlp_grad_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT const char* nlp_grad_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    case 2: return "lam_f";
    case 3: return "lam_g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_grad_name_out(casadi_int i){
  switch (i) {
    case 0: return "f";
    case 1: return "g";
    case 2: return "grad_gamma_x";
    case 3: return "grad_gamma_p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_grad_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_grad_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_grad_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* nlp_grad_f:(x[16],p[])->(f,grad_f_x[16]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0] ? arg[0][8] : 0;
  a1=100.;
  a2=1.;
  a3=arg[0] ? arg[0][0] : 0;
  a3=(a3-a2);
  a4=(1./a3);
  a5=arg[0] ? arg[0][4] : 0;
  a6=casadi_sq(a5);
  a7=2.;
  a6=(a6/a7);
  a6=(a4+a6);
  a6=(a2-a6);
  a6=(a1*a6);
  a8=(a0*a6);
  a9=arg[0] ? arg[0][9] : 0;
  a10=arg[0] ? arg[0][1] : 0;
  a10=(a10-a2);
  a11=(1./a10);
  a12=arg[0] ? arg[0][5] : 0;
  a13=casadi_sq(a12);
  a13=(a13/a7);
  a13=(a11+a13);
  a13=(a2-a13);
  a13=(a1*a13);
  a14=(a9*a13);
  a8=(a8+a14);
  a14=arg[0] ? arg[0][10] : 0;
  a15=arg[0] ? arg[0][2] : 0;
  a15=(a15-a2);
  a16=(1./a15);
  a17=arg[0] ? arg[0][6] : 0;
  a18=casadi_sq(a17);
  a18=(a18/a7);
  a18=(a16+a18);
  a18=(a2-a18);
  a18=(a1*a18);
  a19=(a14*a18);
  a8=(a8+a19);
  a19=arg[0] ? arg[0][11] : 0;
  a20=arg[0] ? arg[0][3] : 0;
  a20=(a20-a2);
  a21=(1./a20);
  a22=arg[0] ? arg[0][7] : 0;
  a23=casadi_sq(a22);
  a23=(a23/a7);
  a23=(a21+a23);
  a2=(a2-a23);
  a2=(a1*a2);
  a23=(a19*a2);
  a8=(a8+a23);
  a23=1.0000000000000000e-003;
  a24=(a0*a9);
  a25=(a0*a14);
  a24=(a24+a25);
  a25=(a0*a19);
  a24=(a24+a25);
  a25=(a9*a14);
  a24=(a24+a25);
  a25=(a9*a19);
  a24=(a24+a25);
  a25=(a14*a19);
  a24=(a24+a25);
  a24=(a24+a9);
  a7=(a7*a14);
  a24=(a24+a7);
  a7=3.;
  a7=(a7*a19);
  a24=(a24+a7);
  a24=(a23*a24);
  a8=(a8-a24);
  a8=(-a8);
  if (res[0]!=0) res[0][0]=a8;
  a4=(a4/a3);
  a3=(a1*a0);
  a4=(a4*a3);
  a4=(-a4);
  if (res[1]!=0) res[1][0]=a4;
  a11=(a11/a10);
  a10=(a1*a9);
  a11=(a11*a10);
  a11=(-a11);
  if (res[1]!=0) res[1][1]=a11;
  a16=(a16/a15);
  a15=(a1*a14);
  a16=(a16*a15);
  a16=(-a16);
  if (res[1]!=0) res[1][2]=a16;
  a21=(a21/a20);
  a1=(a1*a19);
  a21=(a21*a1);
  a21=(-a21);
  if (res[1]!=0) res[1][3]=a21;
  a5=(a5+a5);
  a21=5.0000000000000000e-001;
  a3=(a21*a3);
  a5=(a5*a3);
  if (res[1]!=0) res[1][4]=a5;
  a12=(a12+a12);
  a10=(a21*a10);
  a12=(a12*a10);
  if (res[1]!=0) res[1][5]=a12;
  a17=(a17+a17);
  a15=(a21*a15);
  a17=(a17*a15);
  if (res[1]!=0) res[1][6]=a17;
  a22=(a22+a22);
  a21=(a21*a1);
  a22=(a22*a21);
  if (res[1]!=0) res[1][7]=a22;
  a22=(a23*a19);
  a21=(a23*a14);
  a22=(a22+a21);
  a21=(a23*a9);
  a22=(a22+a21);
  a22=(a22-a6);
  if (res[1]!=0) res[1][8]=a22;
  a22=(a23*a19);
  a22=(a23+a22);
  a6=(a23*a14);
  a22=(a22+a6);
  a6=(a23*a0);
  a22=(a22+a6);
  a22=(a22-a13);
  if (res[1]!=0) res[1][9]=a22;
  a22=2.0000000000000000e-003;
  a19=(a23*a19);
  a22=(a22+a19);
  a19=(a23*a9);
  a22=(a22+a19);
  a19=(a23*a0);
  a22=(a22+a19);
  a22=(a22-a18);
  if (res[1]!=0) res[1][10]=a22;
  a22=3.0000000000000001e-003;
  a14=(a23*a14);
  a22=(a22+a14);
  a9=(a23*a9);
  a22=(a22+a9);
  a23=(a23*a0);
  a22=(a22+a23);
  a22=(a22-a2);
  if (res[1]!=0) res[1][11]=a22;
  a22=0.;
  if (res[1]!=0) res[1][12]=a22;
  if (res[1]!=0) res[1][13]=a22;
  if (res[1]!=0) res[1][14]=a22;
  if (res[1]!=0) res[1][15]=a22;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_grad_f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void nlp_grad_f_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_grad_f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_grad_f_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_grad_f_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* nlp_grad_f_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_grad_f_name_out(casadi_int i){
  switch (i) {
    case 0: return "f";
    case 1: return "grad_f_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_grad_f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_grad_f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_grad_f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* nlp_hess_l:(x[16],p[],lam_f,lam_g[9])->(hess_gamma_x_x[16x16,22nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=100.;
  a1=arg[0] ? arg[0][8] : 0;
  a2=arg[2] ? arg[2][0] : 0;
  a1=(a1*a2);
  a1=(a0*a1);
  a3=arg[0] ? arg[0][0] : 0;
  a4=1.;
  a3=(a3-a4);
  a5=(1./a3);
  a6=(a5/a3);
  a6=(a6/a3);
  a5=(a5/a3);
  a3=(a5/a3);
  a6=(a6+a3);
  a6=(a1*a6);
  if (res[0]!=0) res[0][0]=a6;
  a6=arg[0] ? arg[0][9] : 0;
  a6=(a6*a2);
  a6=(a0*a6);
  a3=arg[0] ? arg[0][1] : 0;
  a3=(a3-a4);
  a7=(1./a3);
  a8=(a7/a3);
  a8=(a8/a3);
  a7=(a7/a3);
  a3=(a7/a3);
  a8=(a8+a3);
  a8=(a6*a8);
  if (res[0]!=0) res[0][1]=a8;
  a8=arg[0] ? arg[0][10] : 0;
  a8=(a8*a2);
  a8=(a0*a8);
  a3=arg[0] ? arg[0][2] : 0;
  a3=(a3-a4);
  a9=(1./a3);
  a10=(a9/a3);
  a10=(a10/a3);
  a9=(a9/a3);
  a3=(a9/a3);
  a10=(a10+a3);
  a10=(a8*a10);
  if (res[0]!=0) res[0][2]=a10;
  a10=arg[0] ? arg[0][11] : 0;
  a10=(a10*a2);
  a10=(a0*a10);
  a3=arg[0] ? arg[0][3] : 0;
  a3=(a3-a4);
  a4=(1./a3);
  a11=(a4/a3);
  a11=(a11/a3);
  a4=(a4/a3);
  a3=(a4/a3);
  a11=(a11+a3);
  a11=(a10*a11);
  if (res[0]!=0) res[0][3]=a11;
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a6;
  if (res[0]!=0) res[0][6]=a8;
  if (res[0]!=0) res[0][7]=a10;
  a10=(a0*a2);
  a5=(a5*a10);
  a5=(-a5);
  if (res[0]!=0) res[0][8]=a5;
  a5=arg[0] ? arg[0][4] : 0;
  a5=(a5+a5);
  a8=5.0000000000000000e-001;
  a10=(a8*a10);
  a5=(a5*a10);
  if (res[0]!=0) res[0][9]=a5;
  a5=(a0*a2);
  a7=(a7*a5);
  a7=(-a7);
  if (res[0]!=0) res[0][10]=a7;
  a7=arg[0] ? arg[0][5] : 0;
  a7=(a7+a7);
  a5=(a8*a5);
  a7=(a7*a5);
  if (res[0]!=0) res[0][11]=a7;
  a7=1.0000000000000000e-003;
  a7=(a7*a2);
  if (res[0]!=0) res[0][12]=a7;
  a5=(a0*a2);
  a9=(a9*a5);
  a9=(-a9);
  if (res[0]!=0) res[0][13]=a9;
  a9=arg[0] ? arg[0][6] : 0;
  a9=(a9+a9);
  a5=(a8*a5);
  a9=(a9*a5);
  if (res[0]!=0) res[0][14]=a9;
  if (res[0]!=0) res[0][15]=a7;
  if (res[0]!=0) res[0][16]=a7;
  a0=(a0*a2);
  a4=(a4*a0);
  a4=(-a4);
  if (res[0]!=0) res[0][17]=a4;
  a4=arg[0] ? arg[0][7] : 0;
  a4=(a4+a4);
  a8=(a8*a0);
  a4=(a4*a8);
  if (res[0]!=0) res[0][18]=a4;
  if (res[0]!=0) res[0][19]=a7;
  if (res[0]!=0) res[0][20]=a7;
  if (res[0]!=0) res[0][21]=a7;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_hess_l(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void nlp_hess_l_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_hess_l_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_hess_l_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int nlp_hess_l_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* nlp_hess_l_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    case 2: return "lam_f";
    case 3: return "lam_g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_hess_l_name_out(casadi_int i){
  switch (i) {
    case 0: return "hess_gamma_x_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_hess_l_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_hess_l_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_hess_l_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* nlp_jac_g:(x[16],p[])->(g[9],jac_g_x[9x16,20nz]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7;
  a0=5.;
  a1=arg[0] ? arg[0][12] : 0;
  a2=(a0+a1);
  a3=arg[0] ? arg[0][0] : 0;
  a2=(a2-a3);
  if (res[0]!=0) res[0][0]=a2;
  a2=arg[0] ? arg[0][13] : 0;
  a3=(a0+a2);
  a4=1.0000000000000001e-001;
  a5=10.;
  a5=(a2-a5);
  a5=(a4*a5);
  a3=(a3-a5);
  a5=arg[0] ? arg[0][1] : 0;
  a3=(a3-a5);
  if (res[0]!=0) res[0][1]=a3;
  a3=arg[0] ? arg[0][14] : 0;
  a5=(a0+a3);
  a6=5.9999999999999998e-001;
  a7=20.;
  a7=(a3-a7);
  a6=(a6*a7);
  a5=(a5-a6);
  a6=1.;
  a5=(a5-a6);
  a7=arg[0] ? arg[0][2] : 0;
  a5=(a5-a7);
  if (res[0]!=0) res[0][2]=a5;
  a5=arg[0] ? arg[0][15] : 0;
  a0=(a0+a5);
  a7=50.;
  a7=(a5-a7);
  a4=(a4*a7);
  a0=(a0-a4);
  a4=18.;
  a0=(a0-a4);
  a0=(a0-a6);
  a4=arg[0] ? arg[0][3] : 0;
  a0=(a0-a4);
  if (res[0]!=0) res[0][3]=a0;
  a0=100.;
  a4=arg[0] ? arg[0][4] : 0;
  a4=(a0*a4);
  a4=(a4-a1);
  if (res[0]!=0) res[0][4]=a4;
  a4=arg[0] ? arg[0][5] : 0;
  a4=(a0*a4);
  a4=(a4-a2);
  if (res[0]!=0) res[0][5]=a4;
  a4=arg[0] ? arg[0][6] : 0;
  a4=(a0*a4);
  a4=(a4-a3);
  if (res[0]!=0) res[0][6]=a4;
  a4=arg[0] ? arg[0][7] : 0;
  a4=(a0*a4);
  a4=(a4-a5);
  if (res[0]!=0) res[0][7]=a4;
  a4=arg[0] ? arg[0][8] : 0;
  a5=arg[0] ? arg[0][9] : 0;
  a4=(a4+a5);
  a5=arg[0] ? arg[0][10] : 0;
  a4=(a4+a5);
  a5=arg[0] ? arg[0][11] : 0;
  a4=(a4+a5);
  a4=(a4-a6);
  if (res[0]!=0) res[0][8]=a4;
  a4=-1.;
  if (res[1]!=0) res[1][0]=a4;
  if (res[1]!=0) res[1][1]=a4;
  if (res[1]!=0) res[1][2]=a4;
  if (res[1]!=0) res[1][3]=a4;
  if (res[1]!=0) res[1][4]=a0;
  if (res[1]!=0) res[1][5]=a0;
  if (res[1]!=0) res[1][6]=a0;
  if (res[1]!=0) res[1][7]=a0;
  if (res[1]!=0) res[1][8]=a6;
  if (res[1]!=0) res[1][9]=a6;
  if (res[1]!=0) res[1][10]=a6;
  if (res[1]!=0) res[1][11]=a6;
  if (res[1]!=0) res[1][12]=a6;
  if (res[1]!=0) res[1][13]=a4;
  a6=9.0000000000000002e-001;
  if (res[1]!=0) res[1][14]=a6;
  if (res[1]!=0) res[1][15]=a4;
  a0=4.0000000000000002e-001;
  if (res[1]!=0) res[1][16]=a0;
  if (res[1]!=0) res[1][17]=a4;
  if (res[1]!=0) res[1][18]=a6;
  if (res[1]!=0) res[1][19]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_jac_g(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void nlp_jac_g_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_jac_g_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_jac_g_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_jac_g_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* nlp_jac_g_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_jac_g_name_out(casadi_int i){
  switch (i) {
    case 0: return "g";
    case 1: return "jac_g_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_jac_g_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_jac_g_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_jac_g_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
